### ISSUE TITLE
strange pigeon log

### ISSUE THREAD

**Issue by andrii1890** [palomachain/paloma#1003]
pigeon v.1.9.1 logs and after some time got jailed
```time="2023-10-05T20:37:58Z" level=info msg="relayer loop"
time="2023-10-05T20:37:58Z" level=info msg="signer loop"
time="2023-10-05T20:37:58Z" level=info msg="attester loop" x-correlation-id=ckfht9jusabhtbe25qo0
time="2023-10-05T20:37:58Z" level=info msg="checking if validator is staking"
time="2023-10-05T20:37:58Z" level=info msg="event watcher loop" x-correlation-id=ckfht9jusabhtbe25qq0
time="2023-10-05T20:37:58Z" level=info msg="validator is staking"
time="2023-10-05T20:37:58Z" level=error msg="couldn't get events" action=handle-gravity-batch-send-events chain-reference-id=base-main error="block range too large" x-correlation-id=ckfht9jusabhtbe25qq0
time="2023-10-05T20:37:58Z" level=error msg="error returned in process loop" err="block range too large"
time="2023-10-05T20:37:59Z" level=info msg="attester loop" x-correlation-id=ckfht9rusabhtbe25qr0
time="2023-10-05T20:37:59Z" level=info msg="relayer loop"```

**Comment by taariq** [comment]
@andrii1890 will you add your .pigeon/config.yaml settings to this ticket?

**Comment by andrii1890** [comment]
```
loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: messenger
  call-timeout: 20s
  keyring-dir: /home/paloma/.paloma
  keyring-type: os
  keyring-pass-env-name: PASSWORD
  signing-key: wallet
  base-rpc-url: http://127.0.0.1:10657
  gas-adjustment: 3.0
  gas-prices: 0.01ugrain
  account-prefix: paloma
```
