### ISSUE TITLE
bug: pigeon having incorrect chain and chain info mismatch errors

### ISSUE THREAD

**Issue by kj89** [palomachain/paloma#1021]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Pigeon is having this `incorrect chain` and `chain info mismatch` errors all over.

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

paloma 1.9.2
pigeon v1.9.4 (e4c619afb57c01b87b9db80353c9c257aef407bb)
```
# ansible-cosmos, Playbooks for blockchain projects
# Copyright (C) 2023  kjnodes Team
---
health-check-port: 5757
loop-timeout: 5s

paloma:
  chain-id: 'messenger'
  call-timeout: 20s
  keyring-dir: /home/paloma/.paloma
  keyring-pass-env-name: PASSWORD
  keyring-type: file
  signing-key: wallet
  base-rpc-url: http://localhost:11057
  gas-adjustment: 2
  gas-prices: 0.01ugrain
  account-prefix: paloma

evm:
  eth-main:
    chain-id: 1
    base-rpc-url: xxx
    keyring-pass-env-name: PASSWORD
    signing-key: xxx
    keyring-dir: /home/paloma/.pigeon/keys/evm/eth-main
    gas-adjustment: 2
    tx-type: 2
  bnb-main:
    chain-id: 56
    base-rpc-url: xxx
    keyring-pass-env-name: PASSWORD
    signing-key: xxx
    keyring-dir: /home/paloma/.pigeon/keys/evm/bnb-main
    gas-adjustment: 2
    tx-type: 0
  matic-main:
    chain-id: 137
    base-rpc-url: xxx
    keyring-pass-env-name: PASSWORD
    signing-key: xxx
    keyring-dir: /home/paloma/.pigeon/keys/evm/matic-main
    gas-adjustment: 2
    tx-type: 2
  op-main:
    chain-id: 10
    base-rpc-url: xxx
    keyring-pass-env-name: PASSWORD
    signing-key: xxx
    keyring-dir: /home/paloma/.pigeon/keys/evm/op-main
    gas-adjustment: 2
    tx-type: 2
  kava-main:
    chain-id: 2222
    base-rpc-url: xxx
    keyring-pass-env-name: PASSWORD
    signing-key: xxx
    keyring-dir: /home/paloma/.pigeon/keys/evm/kava-main
    gas-adjustment: 2
    tx-type: 2
  base-main:
    chain-id: 8453
    base-rpc-url: xxx
    keyring-pass-env-name: PASSWORD
    signing-key: xxx
    keyring-dir: /home/paloma/.pigeon/keys/evm/base-main
    gas-adjustment: 2
    tx-type: 2
```

Here is log file: https://gist.github.com/kj89/7949e19ac875fe22a500cae437c09db8

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Start pigeon service

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

No errors in the log.
