### ISSUE TITLE
bug: pigeon having incorrect chain and chain info mismatch errors

### ISSUE THREAD

**Issue by mesahin001** [palomachain/paloma#1053]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Pigeon is having this incorrect chain and chain info mismatch errors all over.

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

palomad version
1.10.1
pigeon version
App version: v1.10.1
Build commit hash: f36e11b5cc77d352a6cb444f98a795565ddd26f2

config.yaml

```
loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: messenger
  call-timeout: 20s
  keyring-dir: $HOME/.paloma/
  keyring-type: os
  keyring-pass-env-name: PALOMA_KEYRING_PASS
  signing-key: wallet
  base-rpc-url: http://localhost:26657
  gas-adjustment: 3.0
  gas-prices: 0.001ugrain
  account-prefix: paloma
evm:
  eth-main:
    chain-id: 1
    base-rpc-url: ${ETH_RPC_URL}
    keyring-pass-env-name: ETH_PASSWORD
    signing-key: ${ETH_SIGNING_KEY}
    keyring-dir: $HOME/.pigeon/keys/evm/eth-main
    gas-adjustment: 2
    tx-type: 2
  bnb-main:
    chain-id: 56
    base-rpc-url: ${BSC_RPC_URL}
    keyring-pass-env-name: BSC_PASSWORD
    signing-key: ${BSC_SIGNING_KEY}
    keyring-dir: $HOME/.pigeon/keys/evm/bnb-main
    gas-adjustment: 1
    tx-type: 0
  matic-main:
    chain-id: 137
    base-rpc-url: ${MATIC_RPC_URL}
    keyring-pass-env-name: MATIC_PASSWORD
    signing-key: ${MATIC_SIGNING_KEY}
    keyring-dir: $HOME/.pigeon/keys/evm/matic-main
    gas-adjustment: 2
    tx-type: 2
  op-main:
    chain-id: 10
    base-rpc-url: ${OP_RPC_URL}
    keyring-pass-env-name: OP_PASSWORD
    signing-key: ${OP_SIGNING_KEY}
    keyring-dir: /root/.pigeon/keys/evm/op-main
    gas-adjustment: 2
    tx-type: 2
  kava-main:
    chain-id: 2222
    base-rpc-url: ${KAVA_RPC_URL}
    keyring-pass-env-name: KAVA_PASSWORD
    signing-key: ${KAVA_SIGNING_KEY}
    keyring-dir: /root/.pigeon/keys/evm/kava-main
    gas-adjustment: 2
    tx-type: 2
  base-main:
    chain-id: 8453
    base-rpc-url: ${BASE_RPC_URL}
    keyring-pass-env-name: BASE_PASSWORD
    signing-key: ${BASE_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/base-main
    gas-adjustment: 1
    tx-type: 2
  arb-main:
    chain-id: 42161
    base-rpc-url: ${ARB_RPC_URL}
    keyring-pass-env-name: ARB_PASSWORD
    signing-key: ${ARB_SIGNING_KEY}
    keyring-dir: /root/.pigeon/keys/evm/arb-main
    gas-adjustment: 2
    tx-type: 2
  gnosis-main:
    chain-id: 100
    base-rpc-url: ${GNOSIS_RPC_URL}
    keyring-pass-env-name: GNOSIS_PASSWORD
    signing-key: ${GNOSIS_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/gnosis-main
    gas-adjustment: 2
    tx-type: 2`
```

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

restart pigeon service

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

no error

Gist log file: https://gist.github.com/mesahin001/522f1a9f80bb1de5a73fceff072c604a
