### ISSUE TITLE
pigeon errors "execution reverted"

### ISSUE THREAD

**Issue by rektDAOclub** [palomachain/paloma#1282]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Sometime there is errors in pigeond logs:
```
time="2024-09-04T08:00:50+03:00" level=warning msg="Failed to estimate messages" error="there are 1 errors in the group:\nerror  1: original error: call_compass error: execution reverted\nenriched fields:\nmessage id[uint64] = 0x438dd\nmessage type[*types.Message_UpdateValset] = &types.Message_UpdateValset{UpdateValset:(*types.UpdateValset)(0xc001680518)}\n\n"
time="2024-09-04T08:00:50+03:00" level=info msg="No valid estimates, skipping" action=estimate message-ids="[276701]" messages-to-estimate="[276701]" queue-name=evm/blast-main/evm-turnstone-message
```

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

palomad v.2.1.1
pigeond v2.1.0 commit hash: 870a1ba3bb0454a139be3cbedd4ed13b4955129a

```
  blast-main:
    chain-id: 81457
    base-rpc-url: ${BLAST_RPC_URL}
    keyring-pass-env-name: BLAST_PASSWORD
    signing-key: ${BLAST_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/blast-main
    gas-adjustment: 2
    tx-type: 2
```

Blast RPC from nodies, same errors with ankr, din dev, blastapi rpcs

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Did nothing

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>
