### ISSUE TITLE
Bug: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#500]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Fatal error: unexpected signal during runtime execution. See full crash log:
https://gist.github.com/kj89/a5909a0be32b755e36ffc600cce4e55d

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

palomad start crashes.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

palomad should run without runtime execution errors.

**Comment by kj89** [comment]
pigeon configuration file:
```
loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: paloma-testnet-10
  call-timeout: 20s
  keyring-dir: /root/.paloma
  keyring-type: test
  keyring-pass-env-name: PASSWORD
  signing-key: wallet
  base-rpc-url: http://localhost:10657
  gas-adjustment: 2.0
  gas-prices: 0.001ugrain
  account-prefix: paloma

evm:
  eth-main:
    chain-id: 1
    base-rpc-url: https://eth-mainnet.g.alchemy.com/v2/UTvcOqKiUstXbmcsDIgAISrq4b45h3Xk
    keyring-pass-env-name: PASSWORD
    signing-key: 0x63f55bc560e981d53e1f5bb3643e3a96d26fc635
    keyring-dir: /root/.pigeon/keys/evm/eth-main
```
