### ISSUE TITLE
Constant jail bug

### ISSUE THREAD

**Issue by secard51** [palomachain/paloma#506]
**config.yalm** 

```
loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: paloma-testnet-10
  call-timeout: 20s
  keyring-dir: ~/.paloma
  keyring-pass-env-name: PALOMA_KEYRING_PASS
  keyring-type: os
  signing-key: ${VALIDATOR}
  base-rpc-url: http://localhost:27657
  gas-adjustment: 1.5
  gas-prices: 0.001ugrain
  account-prefix: paloma

evm:
  eth-main:
    chain-id: 1
    base-rpc-url: https://mainnet.infura.io/v3/bc855d0d365342f38c26921f4974f5ac
    keyring-pass-env-name: ETH_PASSWORD
    signing-key: ${ETH_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/eth-main

  bsc-main:
    chain-id: 56
    base-rpc-url: https://bsc-mainnet.gateway.pokt.network/v1/lb/6331f8435bbcf1003b4615d7
    keyring-pass-env-name: "BSC_PASSWORD"
    signing-key: ${BSC_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/bsc-main
    gas-adjustment: 1.2
```
    
    
    **env.sh**
    
```
export PALOMA_KEYRING_PASS=Ataman51
export ETH_RPC_URL=https://mainnet.infura.io/v3/bc855d0d365342f38c26921f4974f5ac
export ETH_PASSWORD=Ataman51
export ETH_SIGNING_KEY=9d5dbf17ed3597fff2a4ab4f4e620f918fe4c372
export VALIDATOR=SECARD
export PIGEON_HEALTHCHECK_PORT=5757
export BSC_SIGNING_KEY=9d5dbf17ed3597fff2a4ab4f4e620f918fe4c372
export BSC_PASSWORD=Ataman51
export BSC_RPC_URL=https://bsc-mainnet.gateway.pokt.network/v1/lb/6331f8435bbcf1003b4615d7




```
![problem](https://user-images.githubusercontent.com/99989596/192709789-69bf729f-78f3-47ea-9da0-497b7802b29f.png)
