### ISSUE TITLE
Validator stops signing blocks without any errors

### ISSUE THREAD

**Issue by hdmiimdh** [palomachain/paloma#772]
I moved my validator to a new machine and when I do unjail, it's successfully signing blocks for couple of minutes. After that it stops and I can't see anything suspicious in the logs. Attaching screenshots of how the logs look like at the moment of validator stops signing. 

<img width="1197" alt="Pigeon" src="https://user-images.githubusercontent.com/27004732/225243506-118bf9b9-e8ab-4b3d-8127-0f1a2e7e6e8d.png">
<img width="1200" alt="Paloma" src="https://user-images.githubusercontent.com/27004732/225243523-5cd4696d-9759-4c6d-b642-22d0caa62a28.png">
<img width="1301" alt="Explorer" src="https://user-images.githubusercontent.com/27004732/225243603-bb081a93-a779-4164-8e36-7ab06bcffe04.png">

Paloma version: 
v0.11.6

Pigeon version:
App version: v0.11.5
Build commit hash: cd14972b74003d3613963f552752e6bcde826fe4

Paloma wallet: 
https://paloma.explorers.guru/account/paloma1hj4lxqp05ntjl6ezu3qn9eyedp5p4fpdwu8gxj

ETH wallet: 
https://etherscan.io/address/0xae318806f552f489aa73b7e9150b5c167a85225f

There should be no issue with configs as the same config file was working fine before I moved. Anyway attaching.

```
loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: messenger
  call-timeout: 20s
  keyring-dir: ~/.paloma
  keyring-pass-env-name: PALOMA_KEYRING_PASS
  keyring-type: os
  signing-key: wallet
  base-rpc-url: http://localhost:30657
  gas-adjustment: 2
  gas-prices: 0.01ugrain
  account-prefix: paloma

evm:
  eth-main:
    chain-id: 1
    base-rpc-url: ${ETH_RPC_URL}
    keyring-pass-env-name: "ETH_PASSWORD"
    signing-key: ${ETH_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/eth-main
    gas-adjustment: 2.5
    tx-type: 2
```

The expected behavior validator should not be jailed after you unjail it.
