### ISSUE TITLE
bug: pigeon err occurred and jailed.

### ISSUE THREAD

**Issue by Richard-provalidator** [palomachain/paloma#993]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

{WRITE YOUR ANSWER HERE}

first we got err msg on pigeon at 03:59:52Z and after jailed, same err msg once more.

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i> 1.8.2
<i>Write down pigeon version.</i> 1.8.2
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>

</details>

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>
[pigeon err.txt](https://github.com/palomachain/paloma/files/12722126/pigeon.err.txt)

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by taariq** [comment]
I see the error: **polygon-mainnet.g.alchemy.com | 502: Bad gateway**

It appears that the Alchemy endpoint for Polygon was failing.We recommend using another Polygon MATIC provider.

**Comment by taariq** [comment]
This is a Alchemy issue. Closing.

**Comment by taariq** [comment]
Please update your .pigeon/config.yaml to ensure your pigeon can insert messages into the block

```
loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: messenger
  call-timeout: 20s
  keyring-dir: ~/.paloma
  keyring-pass-env-name: PALOMA_KEYRING_PASS
  keyring-type: os
  signing-key: ${VALIDATOR}
  base-rpc-url: http://localhost:26657
  gas-adjustment: 3.0
  gas-prices: 0.01ugrain
  account-prefix: paloma
  ```
