### ISSUE TITLE
bug: jailed for no apparent reason

### ISSUE THREAD

**Issue by k4b3z4** [palomachain/paloma#994]
I don't see an error in RPC to justify jailing.
I attach logs that capture the moment of the bird's landing
[pigeond.jailed.log](https://github.com/palomachain/paloma/files/12744437/pigeond.jailed.log)

**Comment by taariq** [comment]
This will be fixed in the coming v1.9.0 upgrades tomorrow and Friday. Closing for now.

**Comment by taariq** [comment]
Please update your .pigeon/config.yaml to ensure your pigeon can insert messages into the block

```
loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: messenger
  call-timeout: 20s
  keyring-dir: ~/.paloma
  keyring-pass-env-name: PALOMA_KEYRING_PASS
  keyring-type: os
  signing-key: ${VALIDATOR}
  base-rpc-url: http://localhost:26657
  gas-adjustment: 3.0
  gas-prices: 0.01ugrain
  account-prefix: paloma
  ```
